### PR TITLE
Implemented Time Tracking

### PR DESCRIPTION
**Pull request by MrSoUndso**
If the current day does not match the saved day, the reset() function 
gets called. Currently this reloads the page, as the state of the tasks 
is not yet getting saved.

Happy Hacktoberfest everyone!

### CODE REVIEW

**Comment by MrSoUndso** [comment]
Added the functionallity (not the visuals) to streaks #4

**Comment by mepda** [comment]
Hi there, just wondering if you can clarify as to the first value of the array you're passing into local storage is? And why it looks like this (what's the three doing there?):
image

**Comment by MrSoUndso** [comment]
The first value is how many days the streak has lasted

**Comment by MrSoUndso** [comment]
The three is a slip up on my side, i forgot to remove it after testing

**Comment by MrSoUndso** [comment]
Fixed it, should work as intended now! :+1:

**Comment by mepda** [comment]
Cool! Thanks!

**Pull request merged**
